#!/usr/bin/env python3
"""
This module contains a coroutine that uses asynchronous comprehension
to collect random numbers generated by an asynchronous generator.
"""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Uses an asynchronous comprehension to collect 10 random numbers from an
    async generator.

    Returns:
        list: A list of 10 random numbers.
    """
    return [i async for i in async_generator()]
